export const FETCH_COUNTERS_SUCCESS = 'FETCH_COUNTERS_SUCCESS'
export const FETCH_COUNTERS_PENDING = 'FETCH_COUNTERS_PENDING'
export const FETCH_COUNTERS_ERROR = 'FETCH_COUNTERS_ERROR'

export const CREATE_COUNTERS_SUCCESS = 'CREATE_COUNTERS_SUCCESS'
export const CREATE_COUNTERS_PENDING = 'CREATE_COUNTERS_PENDING'
export const CREATE_COUNTERS_ERROR = 'CREATE_COUNTERS_ERROR'
